// Generated by tools/gen_params.py from tools/param_ids.json and ui/ui_effects_data.c.
// Do not edit; change the registry or the UI and rerun the script.
#pragma once
#include <stdint.h>

#define PARAM_ID_MASTER_VOLUME 0x0001
#define PARAM_ID_MASTER_MUTE   0x0002

// Wire effect id (SLP_FX_*) per FX_* index in ui_effects_data.h.
static const uint8_t k_fx_wire_id[12] = {
     1, // FX_GATE
     2, // FX_COMP
     3, // FX_EQ
     4, // FX_DRIVE
     5, // FX_AMP
     6, // FX_OCTAVE
     7, // FX_CHORUS
     8, // FX_PHASER
     9, // FX_TREMOLO
    10, // FX_DELAY
    11, // FX_REVERB
    12, // FX_CAB
};

// Wire parameter id per [FX_* index][knob index]; 0 = no such knob.
static const uint16_t k_param_id[12][5] = {
    { 0x0100, 0x0101, 0x0102, 0x0103,      0 }, // FX_GATE: thresh, attack, release, range
    { 0x0200, 0x0201, 0x0202, 0x0203, 0x0204 }, // FX_COMP: thresh, ratio, attack, release, gain
    { 0x0300, 0x0301, 0x0302, 0x0303,      0 }, // FX_EQ: low, mid, high, level
    { 0x0400, 0x0401, 0x0402,      0,      0 }, // FX_DRIVE: gain, tone, level
    { 0x0500, 0x0501, 0x0502, 0x0503, 0x0504 }, // FX_AMP: gain, bass, mid, treble, level
    { 0x0600, 0x0601, 0x0602,      0,      0 }, // FX_OCTAVE: mix, octUp, octDown
    { 0x0700, 0x0701, 0x0702,      0,      0 }, // FX_CHORUS: rate, depth, mix
    { 0x0800, 0x0801, 0x0802,      0,      0 }, // FX_PHASER: rate, depth, mix
    { 0x0900, 0x0901,      0,      0,      0 }, // FX_TREMOLO: rate, depth
    { 0x0A00, 0x0A01, 0x0A02, 0x0A03,      0 }, // FX_DELAY: time, feedback, tone, mix
    { 0x0B00, 0x0B01, 0x0B02, 0x0B03,      0 }, // FX_REVERB: decay, predelay, tone, mix
    { 0x0C00, 0x0C01, 0x0C02,      0,      0 }, // FX_CAB: lowcut, highcut, level
};
