// Generated by tools/gen_nam_expected.py from realtime-nam-seed3/scripts/convert_a2.py
// (expected_layer()). Do not edit.
#pragma once

#define NAM_A2_WEIGHT_COUNT 1871
#define NAM_A2_CHANNELS     3
#define NAM_A2_HEAD_TAPS    16
#define NAM_A2_LAYERS       23
static const unsigned char nam_a2_kernels[NAM_A2_LAYERS] = { 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 15, 15, 6, 6, 6, 6, 6, 6, 6 };

// JSON text of the one expected entry of config.layers.
static const char nam_a2_expected_layer[] =
    "{\"input_size\":1,\"condition_size\":1,\"channels\":3,\"bottleneck\":3,\"head\":{\"out_channels\":1,\"kernel_"
    "size\":16,\"bias\":true},\"kernel_sizes\":[6,6,6,6,6,6,6,6,6,6,6,6,6,6,15,15,6,6,6,6,6,6,6],\"dilation"
    "s\":[1,3,7,17,41,101,239,1,3,7,17,41,101,239,1,13,1,3,7,17,41,101,239],\"activation\":[{\"type\":\"Lea"
    "kyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"n"
    "egative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_sl"
    "ope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01}"
    ",{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\""
    "LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\""
    ",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative"
    "_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0."
    "01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type"
    "\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyRe"
    "LU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negative_slope\":0.01},{\"type\":\"LeakyReLU\",\"negat"
    "ive_slope\":0.01}],\"head1x1\":{\"active\":false,\"out_channels\":1,\"groups\":1},\"layer1x1\":{\"active\":tr"
    "ue,\"groups\":1},\"groups_input\":1,\"groups_input_mixin\":1,\"gating_mode\":[\"none\",\"none\",\"none\",\"none"
    "\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"none\",\"no"
    "ne\",\"none\",\"none\",\"none\",\"none\",\"none\"],\"secondary_activation\":[null,null,null,null,null,null,nu"
    "ll,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null],\"slimmable\":"
    "null,\"conv_pre_film\":{\"active\":false,\"shift\":true,\"groups\":1},\"conv_post_film\":{\"active\":false,\""
    "shift\":true,\"groups\":1},\"input_mixin_pre_film\":{\"active\":false,\"shift\":true,\"groups\":1},\"input_m"
    "ixin_post_film\":{\"active\":false,\"shift\":true,\"groups\":1},\"activation_pre_film\":{\"active\":false,\""
    "shift\":true,\"groups\":1},\"activation_post_film\":{\"active\":false,\"shift\":true,\"groups\":1},\"layer1x"
    "1_post_film\":{\"active\":false,\"shift\":true,\"groups\":1},\"head1x1_post_film\":{\"active\":false,\"shift"
    "\":true,\"groups\":1}}";
