idf_component_register(
    SRCS
        "app_main.c"
        "board_init.c"
        "io_expander.c"
        "diag.c"
        "seed_link.c"
        "ui/ui_main.c"
        "ui/ui_effects_data.c"
        "ui/ui_effect_chip.c"
        "ui/ui_knob.c"
        "ui/ui_vertical_slider.c"
        "ui/ui_test_mode.c"
    INCLUDE_DIRS
        "."
        "ui"
)
