#!/usr/bin/env python3
"""Generate firmware/main/nam/nam_a2_expected.h from realtime-nam-seed3/scripts/convert_a2.py.

The ESP32's .nam validator compares a model's layer config against convert_a2.expected_layer()
with Python's equality rules. This writes that expected value as JSON text into a C header,
so the two can never drift apart. Rerun after convert_a2.py changes; --check fails if stale.

    python tools/gen_nam_expected.py [--check]
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT.parent / "reference" / "realtime-nam-seed3" / "scripts"))
import convert_a2  # noqa: E402

OUT = ROOT / "firmware" / "main" / "nam" / "nam_a2_expected.h"


def render():
    text = json.dumps(convert_a2.expected_layer(), separators=(",", ":"))
    chunks = [text[i:i + 96] for i in range(0, len(text), 96)]
    body = "\n".join("    " + json.dumps(c) for c in chunks)
    return ("// Generated by tools/gen_nam_expected.py from realtime-nam-seed3/scripts/convert_a2.py\n"
            "// (expected_layer()). Do not edit.\n"
            "#pragma once\n\n"
            f"#define NAM_A2_WEIGHT_COUNT {convert_a2.WEIGHT_COUNT}\n"
            f"#define NAM_A2_CHANNELS     {convert_a2.CHANNELS}\n"
            f"#define NAM_A2_HEAD_TAPS    {convert_a2.HEAD_TAPS}\n"
            f"#define NAM_A2_LAYERS       {convert_a2.LAYERS}\n"
            f"static const unsigned char nam_a2_kernels[NAM_A2_LAYERS] = {{ {', '.join(map(str, convert_a2.KERNELS))} }};\n\n"
            "// JSON text of the one expected entry of config.layers.\n"
            f"static const char nam_a2_expected_layer[] =\n{body};\n")


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != text:
            print(f"{OUT.relative_to(ROOT)} is out of date: run python tools/gen_nam_expected.py")
            return 1
        print("nam_a2_expected.h OK")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
