#!/usr/bin/env python3
"""Generate the Seed link parameter map from tools/param_ids.json and ui_effects_data.c.

tools/param_ids.json is the append-only registry of wire ids (an id is never renumbered or
reused). This script checks it against the effects and knobs the UI actually defines in
firmware/main/ui/ui_effects_data.c, then writes:

  firmware/main/rig/param_map_gen.h                 FX enum -> wire ids, for the ESP32
  firmware/main/seed_link_proto/slp_params.h        named ids, for the Seed (drop-in)
  docs/SEED_LINK_PROTOCOL.md                        the table between the PARAM TABLE markers

    python tools/gen_params.py           regenerate the outputs
    python tools/gen_params.py --check   exit 1 if the registry or any output is out of date
                                         (the firmware build runs this)
    python tools/gen_params.py --assign  add registry entries for new knobs, then regenerate
"""

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REGISTRY = ROOT / "tools" / "param_ids.json"
EFFECTS_C = ROOT / "firmware" / "main" / "ui" / "ui_effects_data.c"
EFFECTS_H = ROOT / "firmware" / "main" / "ui" / "ui_effects_data.h"
FW_HEADER = ROOT / "firmware" / "main" / "rig" / "param_map_gen.h"
SEED_HEADER = ROOT / "firmware" / "main" / "seed_link_proto" / "slp_params.h"
SPEC = ROOT / "docs" / "SEED_LINK_PROTOCOL.md"
BEGIN, END = "<!-- BEGIN PARAM TABLE (tools/gen_params.py) -->", "<!-- END PARAM TABLE -->"
MAX_KNOBS = 5


class Error(Exception):
    pass


def parse_ui():
    """Return [(FX_ENUM, effect_id, [knob keys])] in FX enum order."""
    header = EFFECTS_H.read_text(encoding="utf-8")
    enum_body = re.search(r"enum\s*\{([^}]*FX_GATE[^}]*)\}", header)
    if not enum_body:
        raise Error(f"{EFFECTS_H}: FX_* enum not found")
    enum_names = re.findall(r"\b(FX_[A-Z]+)\b", re.sub(r"//[^\n]*", "", enum_body.group(1)))

    src = EFFECTS_C.read_text(encoding="utf-8")
    knob_arrays = {}
    for name, body in re.findall(r"static const ui_knob_def_t (k_\w+)\[\]\s*=\s*\{(.*?)\};", src, re.S):
        knob_arrays[name] = re.findall(r'\{\s*"([^"]+)"\s*,\s*"[^"]*"\s*\}', body)
    effects = {}
    for enum, eid, knobs in re.findall(r'\[(FX_[A-Z]+)\]\s*=\s*FX\(\s*"([^"]+)".*?,\s*(k_\w+)\s*\)', src):
        if knobs not in knob_arrays:
            raise Error(f"{EFFECTS_C}: knob array {knobs} for {eid} not found")
        effects[enum] = (eid, knob_arrays[knobs])
    out = []
    for enum in enum_names:
        if enum not in effects:
            raise Error(f"{EFFECTS_C}: no FX() entry for {enum}")
        eid, keys = effects[enum]
        if len(keys) > MAX_KNOBS:
            raise Error(f"{eid}: {len(keys)} knobs, the wire map allows {MAX_KNOBS}")
        out.append((enum, eid, keys))
    return out


def load_registry():
    reg = json.loads(REGISTRY.read_text(encoding="utf-8"))
    ids = {}
    for key, entry in {**reg["params"], **reg.get("retired", {})}.items():
        pid = int(entry["id"], 16)
        if pid in ids:
            raise Error(f"{REGISTRY}: id 0x{pid:04X} used by both {ids[pid]} and {key}")
        ids[pid] = key
    return reg


def check_registry(reg, ui):
    problems = []
    ui_keys = set()
    for _, eid, keys in ui:
        if eid not in reg["effects"]:
            problems.append(f"effect '{eid}' has no wire id in 'effects'")
        for k in keys:
            ui_keys.add(f"{eid}.{k}")
    for key in sorted(ui_keys - set(reg["params"])):
        problems.append(f"knob '{key}' has no id (run gen_params.py --assign)")
    for key in sorted(set(reg["params"]) - ui_keys):
        if not key.startswith("master."):
            problems.append(f"'{key}' is in the registry but not in the UI (move it to 'retired', never delete)")
    return problems


def assign(reg, ui):
    used = {int(e["id"], 16) for e in {**reg["params"], **reg.get("retired", {})}.values()}
    added = []
    for _, eid, keys in ui:
        if eid not in reg["effects"]:
            reg["effects"][eid] = max(reg["effects"].values()) + 1
            added.append(f"effect {eid} = {reg['effects'][eid]}")
        base = reg["effects"][eid] << 8
        for k in keys:
            key = f"{eid}.{k}"
            if key in reg["params"]:
                continue
            pid = next(i for i in range(base, base + 256) if i not in used)
            used.add(pid)
            reg["params"][key] = {"id": f"0x{pid:04X}", "meaning": "TODO: describe"}
            added.append(f"{key} = 0x{pid:04X}")
    return added


def c_ident(key):
    return re.sub(r"([a-z])([A-Z])", r"\1_\2", key).replace(".", "_").upper()


def render_fw_header(reg, ui):
    lines = ["// Generated by tools/gen_params.py from tools/param_ids.json and ui/ui_effects_data.c.",
             "// Do not edit; change the registry or the UI and rerun the script.",
             "#pragma once", "#include <stdint.h>", "",
             "#define PARAM_ID_MASTER_VOLUME " + reg["params"]["master.volume"]["id"],
             "#define PARAM_ID_MASTER_MUTE   " + reg["params"]["master.mute"]["id"], "",
             "// Wire effect id (SLP_FX_*) per FX_* index in ui_effects_data.h.",
             f"static const uint8_t k_fx_wire_id[{len(ui)}] = {{"]
    lines += [f"    {reg['effects'][eid]:>2}, // {enum}" for enum, eid, _ in ui]
    lines += ["};", "",
              "// Wire parameter id per [FX_* index][knob index]; 0 = no such knob.",
              f"static const uint16_t k_param_id[{len(ui)}][{MAX_KNOBS}] = {{"]
    for enum, eid, keys in ui:
        ids = [reg["params"][f"{eid}.{k}"]["id"] for k in keys] + ["0"] * (MAX_KNOBS - len(keys))
        lines.append(f"    {{ {', '.join(f'{i:>6}' for i in ids)} }}, // {enum}: {', '.join(keys)}")
    lines += ["};", ""]
    return "\n".join(lines)


def render_seed_header(reg, ui):
    lines = ["/*",
             " * Seed link parameter ids. Generated by tools/gen_params.py from tools/param_ids.json in",
             " * the esp32-touchscreen-ui repo; do not edit. Values arrive in SET_PARAMS in UI units",
             " * (0..100). Ids are never renumbered; map them by meaning, see docs/SEED_LINK_PROTOCOL.md.",
             " */",
             "#ifndef SLP_PARAMS_H", "#define SLP_PARAMS_H", ""]
    for key, entry in reg["params"].items():
        lines.append(f"#define SLP_P_{c_ident(key):<20} {entry['id']}  /* {entry['meaning']} */")
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def render_table(reg, ui):
    rows = ["| Id | Key | Range | Meaning | On the Seed |", "|---|---|---|---|---|"]
    order = ["master.volume", "master.mute"] + [f"{eid}.{k}" for _, eid, keys in ui for k in keys]
    for key in order:
        e = reg["params"][key]
        rng = "0 or 1" if key == "master.mute" else "0 to 100"
        rows.append(f"| `{e['id']}` | `{key}` | {rng} | {e['meaning']} | {e.get('seed', 'not yet implemented')} |")
    effects = ", ".join(f"{eid} = {reg['effects'][eid]}" for _, eid, _ in ui)
    return "\n".join([BEGIN, "", f"Effect wire ids: {effects}.", "", *rows, "", END])


def spliced_spec(table):
    text = SPEC.read_text(encoding="utf-8") if SPEC.exists() else ""
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        return head + table + rest.split(END, 1)[1]
    return None  # spec not written yet, or markers missing


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--assign", action="store_true")
    args = ap.parse_args()
    try:
        ui = parse_ui()
        reg = load_registry()
        if args.assign:
            added = assign(reg, ui)
            REGISTRY.write_text(json.dumps(reg, indent=2) + "\n", encoding="utf-8")
            print("\n".join(added) or "nothing to assign")
        problems = check_registry(reg, ui)
        if problems:
            raise Error("param registry out of date:\n  " + "\n  ".join(problems))

        outputs = [(FW_HEADER, render_fw_header(reg, ui)), (SEED_HEADER, render_seed_header(reg, ui))]
        spec = spliced_spec(render_table(reg, ui))
        if spec is not None:
            outputs.append((SPEC, spec))

        stale = [p for p, text in outputs if not p.exists() or p.read_text(encoding="utf-8") != text]
        if args.check:
            if stale:
                raise Error("generated files out of date (run python tools/gen_params.py): "
                            + ", ".join(str(p.relative_to(ROOT)) for p in stale))
            print(f"param map OK: {sum(len(k) for _, _, k in ui)} knobs, {len(reg['params'])} ids")
            return 0
        for path, text in outputs:
            if path in stale:
                path.write_text(text, encoding="utf-8", newline="\n")
                print(f"wrote {path.relative_to(ROOT)}")
        return 0
    except Error as e:
        print(f"gen_params: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
