/*
 * Seed link parameter ids. Generated by tools/gen_params.py from tools/param_ids.json in
 * the esp32-touchscreen-ui repo; do not edit. Values arrive in SET_PARAMS in UI units
 * (0..100). Ids are never renumbered; map them by meaning, see docs/SEED_LINK_PROTOCOL.md.
 */
#ifndef SLP_PARAMS_H
#define SLP_PARAMS_H

#define SLP_P_MASTER_VOLUME        0x0001  /* Master output volume. Sent as SET_MASTER; listed here for completeness. */
#define SLP_P_MASTER_MUTE          0x0002  /* Hard mute of the output (1 = muted). Sent as SET_MASTER. */
#define SLP_P_GATE_THRESH          0x0100  /* Noise gate threshold: below this level the gate closes. */
#define SLP_P_GATE_ATTACK          0x0101  /* Noise gate attack: how fast it opens. */
#define SLP_P_GATE_RELEASE         0x0102  /* Noise gate release: how fast it closes. */
#define SLP_P_GATE_RANGE           0x0103  /* Noise gate range: how much it attenuates when closed. */
#define SLP_P_COMP_THRESH          0x0200  /* Compressor threshold. */
#define SLP_P_COMP_RATIO           0x0201  /* Compressor ratio. */
#define SLP_P_COMP_ATTACK          0x0202  /* Compressor attack time. */
#define SLP_P_COMP_RELEASE         0x0203  /* Compressor release time. */
#define SLP_P_COMP_GAIN            0x0204  /* Compressor make-up gain. */
#define SLP_P_EQ_LOW               0x0300  /* EQ low band cut/boost (50 = flat). */
#define SLP_P_EQ_MID               0x0301  /* EQ mid band cut/boost (50 = flat). */
#define SLP_P_EQ_HIGH              0x0302  /* EQ high band cut/boost (50 = flat). */
#define SLP_P_EQ_LEVEL             0x0303  /* EQ output level. */
#define SLP_P_DRIVE_GAIN           0x0400  /* Drive pedal gain (amount of clipping). */
#define SLP_P_DRIVE_TONE           0x0401  /* Drive pedal tone (dark to bright). */
#define SLP_P_DRIVE_LEVEL          0x0402  /* Drive pedal output level. */
#define SLP_P_AMP_GAIN             0x0500  /* Amp input gain into the NAM model (drive). */
#define SLP_P_AMP_BASS             0x0501  /* Amp tone stack bass (50 = flat). */
#define SLP_P_AMP_MID              0x0502  /* Amp tone stack middle (50 = flat). */
#define SLP_P_AMP_TREBLE           0x0503  /* Amp tone stack treble (50 = flat). */
#define SLP_P_AMP_LEVEL            0x0504  /* Amp output level after the model. */
#define SLP_P_OCTAVE_MIX           0x0600  /* Octave effect wet/dry mix. */
#define SLP_P_OCTAVE_OCT_UP        0x0601  /* Level of the octave-up voice. */
#define SLP_P_OCTAVE_OCT_DOWN      0x0602  /* Level of the octave-down voice. */
#define SLP_P_CHORUS_RATE          0x0700  /* Chorus LFO rate. */
#define SLP_P_CHORUS_DEPTH         0x0701  /* Chorus modulation depth. */
#define SLP_P_CHORUS_MIX           0x0702  /* Chorus wet/dry mix. */
#define SLP_P_PHASER_RATE          0x0800  /* Phaser LFO rate. */
#define SLP_P_PHASER_DEPTH         0x0801  /* Phaser sweep depth. */
#define SLP_P_PHASER_MIX           0x0802  /* Phaser wet/dry mix. */
#define SLP_P_TREMOLO_RATE         0x0900  /* Tremolo rate. */
#define SLP_P_TREMOLO_DEPTH        0x0901  /* Tremolo depth. */
#define SLP_P_DELAY_TIME           0x0A00  /* Delay time. */
#define SLP_P_DELAY_FEEDBACK       0x0A01  /* Delay feedback (number of repeats). */
#define SLP_P_DELAY_TONE           0x0A02  /* Delay repeat tone (dark to bright). */
#define SLP_P_DELAY_MIX            0x0A03  /* Delay wet/dry mix. */
#define SLP_P_REVERB_DECAY         0x0B00  /* Reverb decay time. */
#define SLP_P_REVERB_PREDELAY      0x0B01  /* Reverb pre-delay. */
#define SLP_P_REVERB_TONE          0x0B02  /* Reverb tone (dark to bright). */
#define SLP_P_REVERB_MIX           0x0B03  /* Reverb wet/dry mix. */
#define SLP_P_CAB_LOWCUT           0x0C00  /* Cabinet low cut (high-pass) frequency. */
#define SLP_P_CAB_HIGHCUT          0x0C01  /* Cabinet high cut (low-pass) frequency. */
#define SLP_P_CAB_LEVEL            0x0C02  /* Cabinet output level. */

#endif
